import type { Idol, Shloka } from './types';

export const IDOLS: Idol[] = [
  {
    id: 'ganesha',
    name: 'Ganesha',
    emoji: '🐘',
    description: 'Remover of Obstacles & Lord of Beginnings',
    color: '#FF8C00',
    mantra: 'Om Gan Ganapataye Namah',
    mantraDevanagari: 'ॐ गं गणपतये नमः',
    mantraMeaning: 'I bow to Lord Ganesha, the remover of all obstacles and harbinger of wisdom.',
  },
  {
    id: 'lakshmi',
    name: 'Lakshmi',
    emoji: '🪷',
    description: 'Goddess of Wealth, Fortune & Grace',
    color: '#FF69B4',
    mantra: 'Om Shreem Mahalakshmiyei Namah',
    mantraDevanagari: 'ॐ श्रीं महालक्ष्म्यै नमः',
    mantraMeaning: 'Salutations to the Supreme Goddess Lakshmi, who bestows abundance and divine light.',
  },
  {
    id: 'shiva',
    name: 'Shiva',
    emoji: '🔱',
    description: 'The Auspicious One & Lord of Meditation',
    color: '#4169E1',
    mantra: 'Om Namah Shivaya',
    mantraDevanagari: 'ॐ नमः शिवाय',
    mantraMeaning: 'I bow to Lord Shiva, the eternal pure consciousness that resides within all.',
  },
  {
    id: 'durga',
    name: 'Durga',
    emoji: '⚔️',
    description: 'Supreme Goddess of Power & Protection',
    color: '#DC143C',
    mantra: 'Om Dum Durgayei Namah',
    mantraDevanagari: 'ॐ दुं दुर्गायै नमः',
    mantraMeaning: 'I bow to Maa Durga, the unconquerable mother who protects from all negative forces.',
  },
  {
    id: 'krishna',
    name: 'Krishna',
    emoji: '🦚',
    description: 'The Divine Flute & Lord of Cosmic Love',
    color: '#6A0DAD',
    mantra: 'Hare Krishna Hare Krishna, Krishna Krishna Hare Hare',
    mantraDevanagari: 'हरे कृष्ण हरे कृष्ण कृष्ण कृष्ण हरे हरे',
    mantraMeaning: 'O Lord Krishna, O divine energy, engage me in your eternal devotional service.',
  },
  {
    id: 'ram',
    name: 'Ram',
    emoji: '🏹',
    description: 'Maryada Purushottama — The Righteous King',
    color: '#228B22',
    mantra: 'Shri Ram Jai Ram Jai Jai Ram',
    mantraDevanagari: 'श्री राम जय राम जय जय राम',
    mantraMeaning: 'Victory and reverence to Lord Rama, the embodiment of righteousness and truth.',
  },
  {
    id: 'hanuman',
    name: 'Hanuman',
    emoji: '🙏',
    description: 'The Devoted Warrior & Ocean of Courage',
    color: '#FF4500',
    mantra: 'Om Hanumate Namah',
    mantraDevanagari: 'ॐ हनुमते नमः',
    mantraMeaning: 'Salutations to Lord Hanuman, the supreme devotee who dispels fear and grants inner strength.',
  },
  {
    id: 'saraswati',
    name: 'Saraswati',
    emoji: '🎶',
    description: 'Goddess of Wisdom, Arts & Music',
    color: '#00CED1',
    mantra: 'Om Aim Saraswatyai Namah',
    mantraDevanagari: 'ॐ ऐं सरस्वत्यै नमः',
    mantraMeaning: 'I bow to Goddess Saraswati, the source of creative arts, divine knowledge, and speech.',
  },
];

export const DAILY_SHLOKAS: Shloka[] = [
  {
    id: 'shanti-mantra',
    sanskrit: 'ॐ असतो मा सद्गमय । तमसो मा ज्योतिर्गमय । मृत्योर्मा अमृतं गमय ॥',
    transliteration: 'Om Asato Ma Sad-Gamaya | Tamaso Ma Jyotir-Gamaya | Mrityor-Ma Amritam Gamaya',
    meaning: 'Lead me from falsehood to truth; from darkness to light; from mortality to immortality.',
    source: 'Brihadaranyaka Upanishad',
  },
  {
    id: 'gayatri-mantra',
    sanskrit: 'ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात् ॥',
    transliteration: 'Om Bhur Bhuvaḥ Swaḥ Tat-Savitur Vareṇyaṃ Bhargo Devasya Dhīmahi Dhiyo Yo Naḥ Prachodayāt',
    meaning: 'May we meditate on the supreme transcendental radiance of the divine Sun, who illuminates and guides our intellect.',
    source: 'Rigveda (3.62.10)',
  },
  {
    id: 'mahamrityunjaya',
    sanskrit: 'ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम् । उर्वारुकमिव बन्धनान् मृत्योर्मुक्षीय मामृतात् ॥',
    transliteration: 'Om Tryambakaṃ Yajāmahe Sugandhiṃ Puṣṭi-Vardhanam | Urvārukam-Iva Bandhanān Mṛtyor-Mukṣīya Māmṛtāt',
    meaning: 'We meditate on the Three-Eyed Lord Shiva, who nourishes and sustains all life. May He liberate us from bondage and death, unto immortality.',
    source: 'Rigveda (7.59.12)',
  },
  {
    id: 'karmanye-vadhikaraste',
    sanskrit: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन । मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि ॥',
    transliteration: 'Karmaṇy-Evādhikāras-Te Mā Phaleṣu Kadācana | Mā Karma-Phala-Heturbhūr-Mā Te Saṅgo\'stv-Akarmaṇi',
    meaning: 'You have a right only to perform your duty, but never to its fruits. Let not the fruits of action be your motive, nor let your attachment be to inaction.',
    source: 'Bhagavad Gita (2.47)',
  },
  {
    id: 'sarve-bhavantu',
    sanskrit: 'ॐ सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः । सर्वे भद्राणि पश्यन्तु मा कश्चिद् दुःखभाग्भवेत् ॥',
    transliteration: 'Om Sarve Bhavantu Sukhinaḥ Sarve Santu Nirāmayāḥ | Sarve Bhadrāṇi Paśyantu Mā Kaścid Duḥkha-Bhāgbhavet',
    meaning: 'May all beings be happy; may all be healthy and free from illness; may all perceive what is auspicious; may no one suffer.',
    source: 'Universal Peace Prayer',
  },
];
